# Generated by Django 4.2.13 on 2026-02-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0003_quest_zone_has_floors_zone_required_flags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='is_battle_required',
            field=models.BooleanField(default=False, help_text='Ce dresseur bloque le passage et doit être battu avant de quitter la zone.'),
        ),
    ]
