# Generated by Django 4.2.13 on 2026-03-01 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0004_trainer_is_battle_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rivalencounter',
            name='rival',
            field=models.ForeignKey(blank=True, help_text='NULL avec la nouvelle archi RivalTemplate/PlayerRival — résolu per-player.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rival_encounters', to='myPokemonApp.trainer'),
        ),
        migrations.CreateModel(
            name='RivalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_id', models.CharField(max_length=60)),
                ('combat_order', models.IntegerField(default=0, help_text='Ordre chronologique (1=Bourg Palette, 2=Route 22…)')),
                ('rival_starter', models.CharField(choices=[('Bulbasaur', 'Bulbizarre'), ('Charmander', 'Salamèche'), ('Squirtle', 'Carapuce'), ('any', 'Indépendant du starter')], default='any', max_length=20)),
                ('player_starter_match', models.CharField(choices=[('Bulbasaur', 'Bulbizarre'), ('Charmander', 'Salamèche'), ('Squirtle', 'Carapuce'), ('any', 'Indépendant du starter')], default='any', help_text="Starter joueur qui active cette version. 'any' = toutes versions.", max_length=20)),
                ('intro_text', models.TextField(blank=True)),
                ('defeat_text', models.TextField(blank=True)),
                ('victory_text', models.TextField(blank=True)),
                ('pre_battle_text', models.TextField(blank=True)),
                ('post_battle_text', models.TextField(blank=True)),
                ('money_reward', models.IntegerField(default=175)),
                ('team_data', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Template Rival',
                'verbose_name_plural': 'Templates Rival',
                'ordering': ['combat_order', 'player_starter_match'],
                'unique_together': {('quest_id', 'player_starter_match')},
            },
        ),
        migrations.CreateModel(
            name='PlayerRival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(help_text='Trainer joueur propriétaire de cette instance.', on_delete=django.db.models.deletion.CASCADE, related_name='rival_instances', to='myPokemonApp.trainer')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_instances', to='myPokemonApp.rivaltemplate')),
                ('trainer', models.OneToOneField(blank=True, help_text='Trainer NPC matérialisé pour ce joueur (créé à spawn_for_player).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rival_info', to='myPokemonApp.trainer')),
            ],
            options={
                'verbose_name': 'Instance Rival (joueur)',
                'verbose_name_plural': 'Instances Rival (joueur)',
                'unique_together': {('player', 'template')},
            },
        ),
    ]
