# Generated by Django 4.2.13 on 2026-03-04 16:58
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def link_existing_players(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Trainer = apps.get_model('myPokemonApp', 'Trainer')
    for trainer in Trainer.objects.filter(trainer_type='player', user__isnull=True):
        user = User.objects.filter(username=trainer.username).first()
        if user:
            trainer.user = user
            trainer.save(update_fields=['user'])


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myPokemonApp', '0006_ability_playablepokemon_is_hidden_ability_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='trainer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_trainer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(link_existing_players, migrations.RunPython.noop),
    ]