# Generated by Django 4.2.13 on 2026-03-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0015_remove_defeated_trainers_json'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='defeatedtrainer',
            name='unique_defeated_trainer_per_save',
        ),
        migrations.RemoveIndex(
            model_name='defeatedtrainer',
            name='idx_defeated_save_trainer',
        ),
        migrations.RenameField(
            model_name='defeatedtrainer',
            old_name='save',
            new_name='game_save',
        ),
        migrations.AlterUniqueTogether(
            name='defeatedtrainer',
            unique_together={('game_save', 'trainer')},
        ),
        migrations.AddIndex(
            model_name='defeatedtrainer',
            index=models.Index(fields=['game_save', 'trainer'], name='idx_defeated_save_trainer'),
        ),
    ]
