# Generated by Django 4.2.13 on 2026-03-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0019_playablepokemon_gender_pokemon_gender_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='npc_code',
            field=models.CharField(blank=True, help_text="Code stable ex: 'route_1_youngster_ben' — utilisé dans Tiled", max_length=80, null=True, unique=True),
        ),
    ]
