# Generated by Django 4.2.13 on 2026-03-14 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0020_trainer_npc_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('tiled_obj_id', models.IntegerField(help_text="ID de l'objet dans le JSON Tiled (obj.id)")),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPokemonApp.item')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_items', to='myPokemonApp.zone')),
            ],
            options={
                'verbose_name': 'Objet de terrain',
                'verbose_name_plural': 'Objets de terrain',
            },
        ),
        migrations.CreateModel(
            name='PickedUpItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picked_at', models.DateTimeField(auto_now_add=True)),
                ('field_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked_up_by', to='myPokemonApp.fielditem')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked_up_items', to='myPokemonApp.trainer')),
            ],
            options={
                'verbose_name': 'Objet ramassé',
                'verbose_name_plural': 'Objets ramassés',
                'indexes': [models.Index(fields=['trainer', 'field_item'], name='idx_pickedup_trainer_item')],
                'unique_together': {('trainer', 'field_item')},
            },
        ),
        migrations.AddIndex(
            model_name='fielditem',
            index=models.Index(fields=['zone', 'tiled_obj_id'], name='idx_fielditem_zone_tiled'),
        ),
        migrations.AlterUniqueTogether(
            name='fielditem',
            unique_together={('zone', 'tiled_obj_id')},
        ),
    ]
