#!/usr/bin/python3
"""
Script d'ajout des moves Gen 9 (Scarlet/Violet) manquants dans la base.
À exécuter AVANT initLearnableMovesGen9.py.

Moves ajoutés : ceux présents dans les learnsets SV (Gen 9) pour les 151 premiers
Pokémon mais absents des scripts précédents (initializeDatabase.py +
initMissingMovesGen3.py).
"""

from myPokemonApp.models import PokemonMove, PokemonType
import logging

logging.basicConfig(level=logging.INFO)


def add_missing_gen9_moves():
    """Ajoute les moves Gen 9 manquants pour supporter les learnsets SV."""

    logging.info("=" * 70)
    logging.info("AJOUT DES MOVES GEN 9 MANQUANTS (Scarlet/Violet)")
    logging.info("=" * 70)

    types_cache = {}

    def get_type(name):
        if name not in types_cache:
            types_cache[name] = PokemonType.objects.get(name=name)
        return types_cache[name]

    # Format: (nom, type, catégorie, puissance, précision, pp, priorité,
    #          effet, chance_effet, statut_infligé)
    gen9_moves = [
        # GEN 3 NOUVEAUX MOVES (non présents dans initializeDatabase.py)
        ('Aerial Ace',      'flying',    'physical', 60,   100, 20, 0, 'never_miss',         100, None),
        ('Air Cutter',      'flying',    'special',  60,   95,  25, 0, 'high_crit',          100, None),
        ('Blaze Kick',      'fire',      'physical', 85,   90,  10, 0, 'high_crit',          10,  'burn'),
        ('Bullet Seed',     'grass',     'physical', 25,   100, 30, 0, 'multi_hit',          100, None),
        ('Dive',            'water',     'physical', 80,   100, 10, 0, 'charge_turn',        100, None),
        ('Eruption',        'fire',      'special',  150,  100, 5,  0, 'more_damage_if_hp',  100, None),
        ('Extrasensory',    'psychic',   'special',  80,   100, 20, 0, 'flinch',             10,  None),
        ('Fake Tears',      'dark',      'status',   0,    100, 20, 0, 'sharply_lower_special_defense', 100, None),
        ('Feather Dance',   'flying',    'status',   0,    100, 15, 0, 'sharply_lower_attack', 100, None),
        ('Flatter',         'dark',      'status',   0,    100, 15, 0, 'confuse_raise_spatk', 100, None),
        ('Focus Punch',     'fighting',  'physical', 150,  100, 20, 0, 'focus_punch',        100, None),
        ('Grass Whistle',   'grass',     'status',   0,    55,  15, 0, None,                 0,   'sleep'),
        ('Hail',            'ice',       'status',   0,    100, 10, 0, 'hail',               100, None),
        ('Heat Wave',       'fire',      'special',  95,   90,  10, 0, None,                 10,  'burn'),
        ('Howl',            'normal',    'status',   0,    100, 40, 0, 'raise_attack',       100, None),
        ('Hyper Voice',     'normal',    'special',  90,   100, 10, 0, 'sound_based',        100, None),
        ('Icicle Spear',    'ice',       'physical', 25,   100, 30, 0, 'multi_hit',          100, None),
        ('Ingrain',         'grass',     'status',   0,    100, 20, 0, 'ingrain',            100, None),
        ('Knock Off',       'dark',      'physical', 65,   100, 20, 0, 'remove_item',        100, None),
        ('Leaf Blade',      'grass',     'physical', 90,   100, 15, 0, 'high_crit',          100, None),
        ('Luster Purge',    'psychic',   'special',  95,   100, 5,  0, 'lower_special_defense', 50, None),
        ('Magic Coat',      'psychic',   'status',   0,    100, 15, 0, 'magic_coat',         100, None),
        ('Magical Leaf',    'grass',     'special',  60,   100, 20, 0, 'never_miss',         100, None),
        ('Memento',         'dark',      'status',   0,    100, 10, 0, 'memento',            100, None),
        ('Metal Sound',     'steel',     'status',   0,    85,  40, 0, 'sharply_lower_special_defense', 100, None),
        ('Mist Ball',       'psychic',   'special',  95,   100, 5,  0, 'lower_spatk',        50,  None),
        ('Nature Power',    'normal',    'status',   0,    100, 20, 0, 'nature_power',       100, None),
        ('Needle Arm',      'grass',     'physical', 60,   100, 15, 0, 'flinch',             30,  None),
        ('Odor Sleuth',     'normal',    'status',   0,    100, 40, 0, 'odor_sleuth',        100, None),
        ('Overheat',        'fire',      'special',  130,  90,  5,  0, 'sharply_lower_special_attack', 100, None),
        ('Poison Fang',     'poison',    'physical', 50,   100, 15, 0, 'badly_poison',       30,  None),
        ('Psycho Boost',    'psychic',   'special',  140,  90,  5,  0, 'sharply_lower_special_attack', 100, None),
        ('Refresh',         'normal',    'status',   0,    100, 20, 0, 'refresh',            100, None),
        ('Revenge',         'fighting',  'physical', 60,   100, 10, -4, 'double_if_hit',     100, None),
        ('Role Play',       'psychic',   'status',   0,    100, 10, 0, 'role_play',          100, None),
        ('Sand Tomb',       'ground',    'physical', 35,   85,  15, 0, 'trap',               100, None),
        ('Secret Power',    'normal',    'physical', 70,   100, 20, 0, 'secret_power',       30,  None),
        ('Shock Wave',      'electric',  'special',  60,   100, 20, 0, 'never_miss',         100, None),
        ('Signal Beam',     'bug',       'special',  75,   100, 15, 0, 'confuse',            10,  None),
        ('Silver Wind',     'bug',       'special',  60,   100, 5,  0, 'raise_all_stats',    10,  None),
        ('Skill Swap',      'psychic',   'status',   0,    100, 10, 0, 'skill_swap',         100, None),
        ('Sky Uppercut',    'fighting',  'physical', 85,   90,  15, 0, 'hit_flying',         100, None),
        ('Smelling Salts',  'normal',    'physical', 70,   100, 10, 0, 'double_if_paralyzed', 100, None),
        ('Snatch',          'dark',      'status',   0,    100, 10, 4, 'snatch',             100, None),
        ('Spit Up',         'normal',    'special',  1,    100, 10, 0, 'spit_up',            100, None),
        ('Stockpile',       'normal',    'status',   0,    100, 20, 0, 'stockpile',          100, None),
        ('Superpower',      'fighting',  'physical', 120,  100, 5,  0, 'lower_attack_defense', 100, None),
        ('Swallow',         'normal',    'status',   0,    100, 10, 0, 'swallow',            100, None),
        ('Taunt',           'dark',      'status',   0,    100, 20, 0, 'taunt',              100, None),
        ('Tickle',          'normal',    'status',   0,    100, 20, 0, 'lower_attack_defense', 100, None),
        ('Torment',         'dark',      'status',   0,    100, 15, 0, 'torment',            100, None),
        ('Trick',           'psychic',   'status',   0,    100, 10, 0, 'swap_items',         100, None),
        ('Uproar',          'normal',    'special',  90,   100, 10, 0, 'uproar',             100, None),
        ('Volt Tackle',     'electric',  'physical', 120,  100, 15, 0, 'recoil',             10,  'paralysis'),
        ('Water Pulse',     'water',     'special',  60,   100, 20, 0, 'confuse',            20,  None),
        ('Water Sport',     'water',     'status',   0,    100, 15, 0, 'water_sport',        100, None),
        ('Weather Ball',    'normal',    'special',  50,   100, 10, 0, 'weather_ball',       100, None),
        ('Will-O-Wisp',     'fire',      'status',   0,    85,  15, 0, None,                 0,   'burn'),
        ('Yawn',            'normal',    'status',   0,    100, 10, 0, 'yawn',               100, None),
        ('Wish',            'normal',    'status',   0,    100, 10, 0, 'wish',               100, None),

        # MOVES GEN 1 MANQUANTS
        ('Drill Peck',      'flying',    'physical', 80,   100, 20, 0, None,                 0,   None),
        ('Double Kick',     'fighting',  'physical', 30,   100, 30, 0, 'hits_twice',         100, None),
        ('Spikes',          'ground',    'status',   0,    100, 20, 0, 'spikes',             100, None),
        ('Pay Day',         'normal',    'physical', 40,   100, 20, 0, 'pay_day',            100, None),
        ('Faint Attack',    'dark',      'physical', 60,   100, 20, 0, 'never_miss',         100, None),
        ('Mega Punch',      'normal',    'physical', 80,   85,  20, 0, None,                 0,   None),
        ('Mega Kick',       'normal',    'physical', 120,  75,  5,  0, None,                 0,   None),
        ('Counter',         'fighting',  'physical', 1,    100, 20, -5, 'counter',           100, None),
        ('Rage',            'normal',    'physical', 20,   100, 20, 0, 'rage',               100, None),
        ('Glare',           'normal',    'status',   0,    90,  30, 0, None,                 0,   'paralysis'),
        ('Bonemerang',      'ground',    'physical', 50,   90,  10, 0, 'hits_twice',         100, None),
        ('Sharpen',         'normal',    'status',   0,    100, 30, 0, 'raise_attack',       100, None),
        ('Conversion 2',    'normal',    'status',   0,    100, 30, 0, 'conversion2',        100, None),
        ('Substitute',      'normal',    'status',   0,    100, 10, 0, 'substitute',         100, None),
        ('Encore',          'normal',    'status',   0,    100, 5,  0, 'encore',             100, None),
        ('Pursuit',         'dark',      'physical', 40,   100, 20, 0, 'double_fleeing',     100, None),
        ('False Swipe',     'normal',    'physical', 40,   100, 40, 0, 'false_swipe',        100, None),
        ('Flail',           'normal',    'physical', 1,    100, 15, 0, 'low_hp_power',       100, None),
        ('Reversal',        'fighting',  'physical', 1,    100, 15, 0, 'low_hp_power',       100, None),
        ('Spider Web',      'bug',       'status',   0,    100, 10, 0, 'block',              100, None),
        ('Foresight',       'normal',    'status',   0,    100, 40, 0, 'foresight',          100, None),
        ('Destiny Bond',    'ghost',     'status',   0,    100, 5,  -5, 'destiny_bond',      100, None),
        ('Perish Song',     'normal',    'status',   0,    100, 5,  0, 'perish_song',        100, None),
        ('Safeguard',       'normal',    'status',   0,    100, 25, 0, 'safeguard',          100, None),
        ('Attract',         'normal',    'status',   0,    100, 15, 0, 'attract',            100, None),
        ('Mud Slap',        'ground',    'special',  20,   100, 10, 0, 'lower_accuracy',     100, None),
        ('Rollout',         'rock',      'physical', 30,   90,  20, 0, 'rollout',            100, None),
        ('Sweet Kiss',      'fairy',     'status',   0,    75,  10, 0, 'confuse',            100, None),
        ('Belly Drum',      'normal',    'status',   0,    100, 10, 0, 'belly_drum',         100, None),
        ('Fury Cutter',     'bug',       'physical', 40,   95,  20, 0, 'fury_cutter',        100, None),
        ('Attract',         'normal',    'status',   0,    100, 15, 0, 'attract',            100, None),
        ('Magnitude',       'ground',    'physical', 1,    100, 30, 0, 'magnitude',          100, None),
        ('Dynamic Punch',   'fighting',  'physical', 100,  50,  5,  0, 'confuse',            100, None),
        ('Megahorn',        'bug',       'physical', 120,  85,  10, 0, None,                 0,   None),
        ('Night Slash',     'dark',      'physical', 70,   100, 15, 0, 'high_crit',          100, None),
        ('Icy Wind',        'ice',       'special',  55,   95,  15, 0, 'lower_speed',        100, None),
        ('Endure',          'normal',    'status',   0,    100, 10, 0, 'endure',             100, None),
        ('Charm',           'fairy',     'status',   0,    100, 20, 0, 'sharply_lower_attack', 100, None),
        ('Present',         'normal',    'physical', 1,    90,  15, 0, 'present',            100, None),
        ('Frustration',     'normal',    'physical', 1,    100, 20, 0, 'frustration',        100, None),
        ('Return',          'normal',    'physical', 1,    100, 20, 0, 'return',             100, None),
        ('Lock-On',         'normal',    'status',   0,    100, 5,  0, 'lock_on',            100, None),
        ('Zap Cannon',      'electric',  'special',  120,  50,  5,  0, None,                 100, 'paralysis'),
        ('Foresight',       'normal',    'status',   0,    100, 40, 0, 'foresight',          100, None),
        ('Vital Throw',     'fighting',  'physical', 70,   100, 10, -1, 'never_miss',        100, None),
        ('Wake-Up Slap',    'fighting',  'physical', 70,   100, 10, 0, 'double_if_sleep_cure', 100, None),
        ('Discharge',       'electric',  'special',  80,   100, 15, 0, None,                 30,  'paralysis'),
        ('Magnet Rise',     'electric',  'status',   0,    100, 10, 0, 'magnet_rise',        100, None),
        ('Charge',          'electric',  'status',   0,    100, 20, 0, 'charge',             100, None),
        ('Aqua Tail',       'water',     'physical', 90,   90,  10, 0, None,                 0,   None),
        ('Dragon Rush',     'dragon',    'physical', 100,  75,  10, 0, 'flinch',             20,  None),
        ('Dragon Tail',     'dragon',    'physical', 60,   90,  10, -6, 'force_switch',      100, None),
        ('Hurricane',       'flying',    'special',  110,  70,  10, 0, 'confuse',            30,  None),
        ('Psystrike',       'psychic',   'special',  100,  100, 10, 0, 'physical_defense',   100, None),
        ('Ancient Power',   'rock',      'special',  60,   100, 5,  0, 'raise_all_stats',    10,  None),
        ('Twister',         'dragon',    'special',  40,   100, 20, 0, 'flinch',             20,  None),
        ('Double Hit',      'normal',    'physical', 35,   90,  10, 0, 'hits_twice',         100, None),
        ('Mud Shot',        'ground',    'special',  55,   95,  15, 0, 'lower_speed',        100, None),
        ('Rock Polish',     'rock',      'status',   0,    100, 20, 0, 'sharply_raise_speed', 100, None),
        ('Aqua Jet',        'water',     'physical', 40,   100, 20, 1, None,                 0,   None),
        ('Gunk Shot',       'poison',    'physical', 120,  80,  5,  0, None,                 30,  'poison'),
        ('Acid Armor',      'poison',    'status',   0,    100, 20, 0, 'sharply_raise_defense', 100, None),
        ('Wood Hammer',     'grass',     'physical', 120,  100, 15, 0, 'recoil',             100, None),
        ('Leaf Storm',      'grass',     'special',  130,  90,  5,  0, 'sharply_lower_special_attack', 100, None),
        ('Gastro Acid',     'poison',    'status',   0,    100, 10, 0, 'suppress_ability',   100, None),
        ('Sucker Punch',    'dark',      'physical', 70,   100, 5,  1, 'fail_if_not_attacking', 100, None),
        ('Sheer Cold',      'ice',       'special',  1,    30,  5,  0, 'ohko',               100, None),
        ('Mind Reader',     'normal',    'status',   0,    100, 5,  0, 'lock_on',            100, None),
        ('Ice Fang',        'ice',       'physical', 65,   95,  15, 0, 'flinch',             10,  'freeze'),
        ('Rock Blast',      'rock',      'physical', 25,   90,  10, 0, 'multi_hit',          100, None),
        ('Crabhammer',      'water',     'physical', 100,  90,  10, 0, 'high_crit',          100, None),
        ('Spike Cannon',    'normal',    'physical', 20,   100, 15, 0, 'multi_hit',          100, None),
        ('Earth Power',     'ground',    'special',  90,   100, 10, 0, 'lower_special_defense', 10, None),
        ('Outrage',         'dragon',    'physical', 120,  100, 10, 0, 'rampage',            100, None),
        ('Extreme Speed',   'normal',    'physical', 80,   100, 5,  2, None,                 0,   None),
        ('Comet Punch',     'normal',    'physical', 18,   85,  15, 0, 'multi_hit',          100, None),
        ('Sky Attack',      'flying',    'physical', 140,  90,  5,  0, 'charge_turn',        30,  'flinch'),
        ('Mist',            'ice',       'status',   0,    100, 30, 0, 'mist',               100, None),
        ('Focus Energy',    'normal',    'status',   0,    100, 30, 0, 'focus_energy',       100, None),
        ('Mirror Move',     'flying',    'status',   0,    100, 20, 0, 'mirror_move',        100, None),
        ('Powder Snow',     'ice',       'special',  40,   100, 25, 0, None,                 10,  'freeze'),
        ('Ice Shard',       'ice',       'physical', 40,   100, 30, 1, None,                 0,   None),
        ('Razor Shell',     'water',     'physical', 75,   95,  10, 0, 'lower_defense',      50,  None),
        ('Constrict',       'normal',    'physical', 10,   100, 35, 0, 'lower_speed',        10,  None),
        ('Bubblebeam',      'water',     'special',  65,   100, 20, 0, 'lower_speed',        10,  None),
        ('Wing Attack',     'flying',    'physical', 60,   100, 35, 0, None,                 0,   None),
        ('Smokescreen',     'normal',    'status',   0,    100, 20, 0, 'lower_accuracy',     100, None),
        ('Scary Face',      'normal',    'status',   0,    100, 10, 0, 'sharply_lower_speed', 100, None),
        ('Pay Day',         'normal',    'physical', 40,   100, 20, 0, 'pay_day',            100, None),
        ('Arm Thrust',      'fighting',  'physical', 15,   100, 20, 0, 'multi_hit',          100, None),
        ('Aromatherapy',    'grass',     'status',   0,    100, 5,  0, 'heal_team_status',   100, None),
        ('Bounce',          'flying',    'physical', 85,   85,  5,  0, 'charge_turn',        30,  'paralysis'),
        ('Night Slash',     'dark',      'physical', 70,   100, 15, 0, 'high_crit',          100, None),
        ('Power Whip',      'grass',     'physical', 120,  85,  10, 0, None,                 0,   None),
        ('Endeavor',        'normal',    'physical', 0,    100, 5,  0, 'endeavor',           100, None),
        ('Crunch',          'dark',      'physical', 80,   100, 15, 0, 'lower_defense',       20,  None),
        ('Poison Jab',      'poison',    'physical', 80,   100, 20, 0, 'poison',             30,  'poison'),
        ('Softboiled',      'normal',    'status',   0,    100, 10, 0, 'heal',               100, None),
        ('Grudge',          'ghost',     'status',   0,    100, 5,  0, 'grudge',             100, None),
        ('Doubleslap',      'normal',    'physical', 15,   85,  10, 0, 'multi_hit',          100, None),
        ('Gyro Ball',       'steel',     'physical', 0,    100, 5,  0, 'gyro_ball',          100, None),
        ('Mimic',           'normal',    'status',   0,    100, 10, 0, 'mimic',              100, None),
        ('Moonlight',       'fairy',     'status',   0,    100, 5,  0, 'heal',               100, None),
        ('Flame Wheel',     'fire',      'physical', 60,   100, 25, 0, 'burn',               10,  'burn'),
        ('Mud Sport',       'ground',    'status',   0,    100, 15, 0, 'mud_sport',           100, None),
        ('Vicegrip',        'normal',    'physical', 55,   100, 30, 0, 'none',               100, None),
        ('Mirror Coat',     'psychic',   'special',  0,    100, 20, -5, 'mirror_coat',        100, None),
        ('Hi Jump Kick',    'fighting',  'physical', 130,  90,  10, 0, 'high_jump_kick',     100, None),
        ('Copy Cat',        'normal',    'status',   0,    100, 20, 0, 'copycat',             100, None),
        ('Vacuum Wave',     'fighting',  'special',  40,   100, 30, 1, 'none',               100, None),
        ('DoubleSlap',      'normal',    'physical', 15,   85,  10, 0, 'multi_hit',          100, None),
        ('Payback',         'dark',      'physical', 50,   100, 10, 0, 'payback',            100, None),
        ('Power Swap',      'psychic',   'status',   0,    100, 10, 0, 'power_swap',         100, None),
        ('Guard Swap',      'psychic',   'status',   0,    100, 10, 0, 'guard_swap',         100, None),
        # ── MOVES GEN 4 encore manquants ─────────────────────────────────────
        ("Stealth Rock",      "rock",      "status",   0,   100, 20,  0,  "stealth_rock",                100, None),
        ("Close Combat",      "fighting",  "physical", 120, 100, 5,   0,  "lower_defense_special_defense",100, None),
        ("Flare Blitz",       "fire",      "physical", 120, 100, 15,  0,  "recoil",                       10, "burn"),
        ("Aura Sphere",       "fighting",  "special",  80,  100, 20,  0,  "never_miss",                  100, None),
        ("Dark Pulse",        "dark",      "special",  80,  100, 15,  0,  "flinch",                       20, None),
        ("Dragon Pulse",      "dragon",    "special",  85,  100, 10,  0,  None,                            0, None),
        ("Energy Ball",       "grass",     "special",  90,  100, 10,  0,  "lower_special_defense",        10, None),
        ("Flash Cannon",      "steel",     "special",  80,  100, 10,  0,  "lower_special_defense",        10, None),
        ("Giga Impact",       "normal",    "physical", 150, 90,  5,   0,  "recharge",                    100, None),
        ("Ice Punch",         "ice",       "physical", 75,  100, 15,  0,  None,                           10, "freeze"),
        ("Iron Head",         "steel",     "physical", 80,  100, 15,  0,  "flinch",                       30, None),
        ("Poison Jab",        "poison",    "physical", 80,  100, 20,  0,  None,                           30, "poison"),
        ("Power Gem",         "rock",      "special",  80,  100, 20,  0,  None,                            0, None),
        ("Stone Edge",        "rock",      "physical", 100, 80,  5,   0,  "high_crit",                   100, None),
        ("Thunder Fang",      "electric",  "physical", 65,  95,  15,  0,  "flinch",                       10, "paralysis"),
        ("Fire Fang",         "fire",      "physical", 65,  95,  15,  0,  "flinch",                       10, "burn"),
        ("Aqua Tail",         "water",     "physical", 90,  90,  10,  0,  None,                            0, None),
        ("X-Scissor",         "bug",       "physical", 80,  100, 15,  0,  None,                            0, None),
        ("Bug Buzz",          "bug",       "special",  90,  100, 10,  0,  "lower_special_defense",        10, None),
        ("Roost",             "flying",    "status",   0,   100, 10,  0,  "heal_half",                   100, None),
        ("Spikes",            "ground",    "status",   0,   100, 20,  0,  "spikes",                      100, None),
        ("Toxic",             "poison",    "status",   0,   90,  10,  0,  None,                            0, "badly_poisoned"),
        ("Knock Off",         "dark",      "physical", 65,  100, 20,  0,  "remove_item",                 100, None),
        ("U-turn",            "bug",       "physical", 70,  100, 20,  0,  "switch_out",                  100, None),
        ("Volt Switch",       "electric",  "special",  70,  100, 20,  0,  "switch_out",                  100, None),
        ("Aqua Ring",         "water",     "status",   0,   100, 20,  0,  "aqua_ring",                   100, None),
        ("Scald",             "water",     "special",  80,  100, 15,  0,  None,                           30, "burn"),
        ("Sludge Bomb",       "poison",    "special",  90,  100, 10,  0,  None,                           30, "poison"),
        ("Earth Power",       "ground",    "special",  90,  100, 10,  0,  "lower_special_defense",        10, None),
        ("Hex",               "ghost",     "special",  65,  100, 10,  0,  "double_if_status",            100, None),
        ("Shadow Claw",       "ghost",     "physical", 70,  100, 15,  0,  "high_crit",                   100, None),
        ("Seed Bomb",         "grass",     "physical", 80,  100, 15,  0,  None,                            0, None),
        ("Zen Headbutt",      "psychic",   "physical", 80,  90,  15,  0,  "flinch",                       20, None),
        ("Discharge",         "electric",  "special",  80,  100, 15,  0,  None,                           30, "paralysis"),
        ("Lava Plume",        "fire",      "special",  80,  100, 15,  0,  None,                           30, "burn"),
        ("Charge Beam",       "electric",  "special",  50,  90,  10,  0,  "raise_special_attack",         70, None),
        ("Gastro Acid",       "poison",    "status",   0,   100, 10,  0,  "suppress_ability",            100, None),
        ("Payback",           "dark",      "physical", 50,  100, 10,  0,  "payback",                     100, None),
        ("Stealth Rock",      "rock",      "status",   0,   100, 20,  0,  "stealth_rock",                100, None),

        # ── MOVES GEN 5 ──────────────────────────────────────────────────────
        ("Work Up",           "normal",    "status",   0,   100, 30,  0,  "raise_attack_special_attack", 100, None),
        ("Coil",              "poison",    "status",   0,   100, 20,  0,  "raise_attack_defense_accuracy",100, None),
        ("Quiver Dance",      "bug",       "status",   0,   100, 20,  0,  "raise_special_attack_special_defense_speed", 100, None),
        ("Hurricane",         "flying",    "special",  110, 70,  10,  0,  "confuse",                      30, None),
        ("Heat Crash",        "fire",      "physical", 1,   100, 10,  0,  "weight_based",                100, None),
        ("Low Kick",          "fighting",  "physical", 1,   100, 20,  0,  "weight_based",                100, None),
        ("Dragon Tail",       "dragon",    "physical", 60,  90,  10,  -6, "force_switch",                100, None),
        ("Incinerate",        "fire",      "special",  60,  100, 15,  0,  "destroy_berry",               100, None),
        ("Snarl",             "dark",      "special",  55,  95,  15,  0,  "lower_special_attack",        100, None),
        ("Electroweb",        "electric",  "special",  55,  95,  15,  0,  "lower_speed",                 100, None),
        ("Stored Power",      "psychic",   "special",  20,  100, 10,  0,  "power_up_per_stat",           100, None),
        ("Bulldoze",          "ground",    "physical", 60,  100, 20,  0,  "lower_speed",                 100, None),
        ("Rock Slide",        "rock",      "physical", 75,  90,  10,  0,  "flinch",                       30, None),
        ("Acrobatics",        "flying",    "physical", 55,  100, 15,  0,  "double_no_item",              100, None),
        ("Smack Down",        "rock",      "physical", 50,  100, 15,  0,  "ground_flying",               100, None),
        ("Venoshock",         "poison",    "special",  65,  100, 10,  0,  "double_if_poisoned",          100, None),
        ("Psyshock",          "psychic",   "special",  80,  100, 10,  0,  "use_physical_defense",        100, None),
        ("Clear Smog",        "poison",    "special",  50,  100, 15,  0,  "reset_stat_changes",          100, None),
        ("Acid Spray",        "poison",    "special",  40,  100, 20,  0,  "sharply_lower_special_defense",100, None),
        ("Flame Burst",       "fire",      "special",  70,  100, 15,  0,  "splash_damage",               100, None),
        ("Icy Wind",          "ice",       "special",  55,  95,  15,  0,  "lower_speed",                 100, None),
        ("Night Slash",       "dark",      "physical", 70,  100, 15,  0,  "high_crit",                   100, None),

        # ── MOVES GEN 6 ──────────────────────────────────────────────────────
        ("Dazzling Gleam",    "fairy",     "special",  80,  100, 10,  0,  None,                            0, None),
        ("Play Rough",        "fairy",     "physical", 90,  90,  10,  0,  "lower_attack",                 10, None),
        ("Moonblast",         "fairy",     "special",  95,  100, 15,  0,  "lower_special_attack",         30, None),
        ("Misty Terrain",     "fairy",     "status",   0,   100, 10,  0,  "misty_terrain",               100, None),
        ("Electric Terrain",  "electric",  "status",   0,   100, 10,  0,  "electric_terrain",            100, None),
        ("Psychic Terrain",   "psychic",   "status",   0,   100, 10,  0,  "psychic_terrain",             100, None),
        ("Grassy Terrain",    "grass",     "status",   0,   100, 10,  0,  "grassy_terrain",              100, None),
        ("Nuzzle",            "electric",  "physical", 20,  100, 20,  0,  None,                          100, "paralysis"),
        ("Draining Kiss",     "fairy",     "special",  50,  100, 10,  0,  "drain",                       100, None),
        ("Fairy Wind",        "fairy",     "special",  40,  100, 30,  0,  None,                            0, None),
        ("Baby-Doll Eyes",    "fairy",     "status",   0,   100, 30,  1,  "lower_attack",                100, None),
        ("Geomancy",          "fairy",     "status",   0,   100, 10,  0,  "sharply_raise_special_attack_special_defense_speed", 100, None),
        ("Sticky Web",        "bug",       "status",   0,   100, 20,  0,  "sticky_web",                  100, None),
        ("Ion Deluge",        "electric",  "status",   0,   100, 5,   0,  "ion_deluge",                  100, None),
        ("Infestation",       "bug",       "special",  20,  100, 20,  0,  "trap",                        100, None),
        ("Disarming Voice",   "fairy",     "special",  40,  100, 15,  0,  "never_miss",                  100, None),
        ("Aromatherapy",      "grass",     "status",   0,   100, 5,   0,  "heal_team_status",            100, None),
        ("Flower Shield",     "fairy",     "status",   0,   100, 10,  0,  "raise_defense_grass",         100, None),
        ("Crafty Shield",     "fairy",     "status",   0,   100, 10,  3,  "protect_status",              100, None),
        ("Electrify",         "electric",  "status",   0,   100, 20,  0,  "electrify",                   100, None),

        # ── MOVES GEN 7 ──────────────────────────────────────────────────────
        ("Sparkling Aria",    "water",     "special",  90,  100, 10,  0,  "heal_burn",                   100, None),
        ("First Impression",  "bug",       "physical", 90,  100, 10,  2,  "only_first_turn",             100, None),
        ("Baneful Bunker",    "poison",    "status",   0,   100, 10,  4,  "protect_poison",              100, None),
        ("Spirit Shackle",    "ghost",     "physical", 80,  100, 10,  0,  "prevent_switch",              100, None),
        ("Darkest Lariat",    "dark",      "physical", 85,  100, 10,  0,  "ignore_stat_changes",         100, None),
        ("Sparkling Aria",    "water",     "special",  90,  100, 10,  0,  "heal_burn",                   100, None),
        ("High Horsepower",   "ground",    "physical", 95,  95,  10,  0,  None,                            0, None),
        ("Strength Sap",      "grass",     "status",   0,   100, 10,  0,  "heal_lower_attack",           100, None),
        ("Solar Blade",       "grass",     "physical", 125, 100, 10,  0,  "charge_turn",                 100, None),
        ("Liquidation",       "water",     "physical", 85,  100, 10,  0,  "lower_defense",               20, None),
        ("Psychic Fangs",     "psychic",   "physical", 85,  100, 10,  0,  "break_screens",               100, None),
        ("Burning Jealousy",  "fire",      "special",  70,  100, 5,   0,  "burn_if_stat_raised",         100, None),
        ("Lash Out",          "dark",      "physical", 75,  100, 5,   0,  "double_if_stat_lowered",      100, None),
        ("Poltergeist",       "ghost",     "physical", 110, 90,  5,   0,  "fail_no_item",                100, None),
        ("Corrosive Gas",     "poison",    "status",   0,   100, 40,  0,  "remove_item",                 100, None),
        ("Coaching",          "fighting",  "status",   0,   100, 10,  0,  "raise_ally_attack_defense",   100, None),
        ("Pounce",            "bug",       "physical", 50,  100, 20,  0,  "lower_speed",                 100, None),
        ("Trailblaze",        "grass",     "physical", 50,  100, 20,  0,  "raise_speed",                 100, None),

        # ── MOVES GEN 8 ──────────────────────────────────────────────────────
        ("Snap Trap",         "grass",     "physical", 35,  100, 15,  0,  "trap",                        100, None),
        ("Jaw Lock",          "dark",      "physical", 80,  100, 10,  0,  "prevent_switch_both",         100, None),
        ("Dragon Energy",     "dragon",    "special",  150, 100, 5,   0,  "more_damage_if_hp",           100, None),
        ("Eternabeam",        "dragon",    "special",  160, 90,  5,   0,  "recharge",                    100, None),
        ("Scale Shot",        "dragon",    "physical", 25,  90,  20,  0,  "multi_hit_lower_defense",     100, None),
        ("Meteor Beam",       "rock",      "special",  120, 90,  10,  0,  "charge_raise_spatk",          100, None),
        ("Freezing Glare",    "psychic",   "special",  90,  100, 10,  0,  None,                           10, "freeze"),
        ("Fiery Wrath",       "dark",      "special",  90,  100, 10,  0,  "flinch",                       20, None),
        ("Thunderous Kick",   "fighting",  "physical", 90,  100, 10,  0,  "lower_defense",               100, None),
        ("Glacial Lance",     "ice",       "physical", 120, 100, 5,   0,  None,                            0, None),
        ("Astral Barrage",    "ghost",     "special",  120, 100, 5,   0,  None,                            0, None),
        ("Eerie Spell",       "psychic",   "special",  80,  100, 5,   0,  "reduce_pp",                   100, None),
        ("Dire Claw",         "poison",    "physical", 60,  100, 15,  0,  "random_status",                50, None),
        ("Psyshield Bash",    "psychic",   "physical", 70,  90,  10,  0,  "raise_defense",               100, None),
        ("Power Shift",       "normal",    "status",   0,   100, 10,  0,  "swap_attack_defense",         100, None),
        ("Stone Axe",         "rock",      "physical", 65,  90,  15,  0,  "set_stealth_rock",            100, None),
        ("Spring-Up Smash",   "grass",     "physical", 60,  100, 10,  0,  "raise_attack",                100, None),
        ("Infernal Parade",   "ghost",     "special",  60,  100, 15,  0,  "double_if_status",             30, "burn"),
        ("Ceaseless Edge",    "dark",      "physical", 65,  90,  15,  0,  "set_spikes",                  100, None),
        ("Bleakwind Storm",   "flying",    "special",  100, 80,  10,  0,  "lower_speed",                  30, None),
        ("Wildbolt Storm",    "electric",  "special",  100, 80,  10,  0,  None,                           20, "paralysis"),
        ("Sandsear Storm",    "ground",    "special",  100, 80,  10,  0,  None,                           20, "burn"),

        # ── MOVES GEN 9 (Scarlet/Violet) ─────────────────────────────────────
        ("Salt Cure",         "rock",      "status",   0,   100, 15,  0,  "salt_cure",                   100, None),
        ("Triple Dive",       "water",     "physical", 30,  95,  10,  0,  "hits_three_times",            100, None),
        ("Mortal Spin",       "poison",    "physical", 30,  100, 15,  0,  "clear_hazards_poison",        100, None),
        ("Doodle",            "normal",    "status",   0,   100, 10,  0,  "copy_ability",                100, None),
        ("Fillet Away",       "normal",    "status",   0,   100, 10,  0,  "sharply_raise_spatk_speed_lower_hp", 100, None),
        ("Kowtow Cleave",     "dark",      "physical", 85,  100, 10,  0,  "never_miss",                  100, None),
        ("Flower Trick",      "grass",     "physical", 70,  100, 10,  0,  "always_crit",                 100, None),
        ("Torch Song",        "fire",      "special",  80,  100, 10,  0,  "raise_special_attack",        100, None),
        ("Aqua Step",         "water",     "physical", 80,  100, 10,  0,  "raise_speed",                 100, None),
        ("Raging Bull",       "normal",    "physical", 90,  100, 10,  0,  "break_screens_type_change",   100, None),
        ("Make It Rain",      "steel",     "special",  120, 100, 5,   0,  "lower_special_attack",        100, None),
        ("Ruination",         "dark",      "special",  1,   90,  10,  0,  "half_hp",                     100, None),
        ("Wave Crash",        "water",     "physical", 120, 100, 10,  0,  "recoil",                      100, None),
        ("Chloroblast",       "grass",     "special",  150, 95,  5,   0,  "recoil",                      100, None),
        ("Mountain Gale",     "ice",       "physical", 100, 85,  10,  0,  "flinch",                       30, None),
        ("Victory Dance",     "fighting",  "status",   0,   100, 10,  0,  "raise_attack_defense_speed",  100, None),
        ("Headlong Rush",     "ground",    "physical", 120, 100, 5,   0,  "lower_defense_special_defense",100, None),
        ("Barb Barrage",      "poison",    "physical", 60,  100, 10,  0,  "double_if_poisoned_badly",     50, "poison"),
        ("Esper Wing",        "psychic",   "special",  80,  100, 10,  0,  "raise_speed_high_crit",       100, None),
        ("Bitter Malice",     "ghost",     "special",  75,  100, 10,  0,  "lower_attack",                100, None),
        ("Shelter",           "steel",     "status",   0,   100, 10,  0,  "sharply_raise_defense",       100, None),
        ("Triple Arrows",     "fighting",  "physical", 50,  100, 10,  0,  "high_crit_lower_defense_flinch",100, None),
        ("Infernal Parade",   "ghost",     "special",  60,  100, 15,  0,  "double_if_status_burn",        30, "burn"),
        ("Tera Blast",        "normal",    "special",  80,  100, 10,  0,  "tera_type",                   100, None),
        ("Silk Trap",         "bug",       "status",   0,   100, 10,  4,  "protect_lower_speed",         100, None),
        ("Axe Kick",          "fighting",  "physical", 120, 90,  10,  0,  "crash_confuse",               30, None),
        ("Last Respects",     "ghost",     "physical", 50,  100, 10,  0,  "power_per_fainted_ally",      100, None),
        ("Lumina Crash",      "psychic",   "special",  80,  100, 10,  0,  "sharply_lower_special_defense",100, None),
        ("Order Up",          "dragon",    "physical", 80,  100, 10,  0,  "raise_stat_based_on_tatsugiri",100, None),
        ("Jet Punch",         "water",     "physical", 60,  100, 15,  1,  None,                            0, None),
        ("Spicy Extract",     "grass",     "status",   0,   100, 15,  0,  "sharply_raise_attack_lower_defense",100, None),
        ("Spin Out",          "steel",     "physical", 100, 100, 5,   0,  "sharply_lower_speed",         100, None),
        ("Population Bomb",   "normal",    "physical", 20,  90,  10,  0,  "hits_up_to_ten",              100, None),
        ("Ice Spinner",       "ice",       "physical", 80,  100, 15,  0,  "clear_terrain",               100, None),
        ("Glaive Rush",       "dragon",    "physical", 120, 100, 5,   0,  "vulnerable_next_turn",        100, None),
        ("Revival Blessing",  "normal",    "status",   0,   100, 1,   0,  "revive_ally",                 100, None),
        ("Salt Cure",         "rock",      "status",   0,   100, 15,  0,  "salt_cure",                   100, None),
        ("Rage Fist",         "ghost",     "physical", 50,  100, 10,  0,  "power_per_hit_taken",         100, None),
        ("Armor Cannon",      "fire",      "special",  120, 100, 5,   0,  "lower_defense_special_defense",100, None),
        ("Bitter Blade",      "fire",      "physical", 90,  100, 10,  0,  "drain",                       100, None),
        ("Double Shock",      "electric",  "physical", 120, 100, 5,   0,  "lose_electric_type",          100, None),
        ("Gigaton Hammer",    "steel",     "physical", 160, 100, 5,   0,  "cannot_use_consecutively",    100, None),
        ("Comeuppance",       "dark",      "physical", 1,   100, 10,  -7, "payback_max",                 100, None),
        ("Aqua Cutter",       "water",     "physical", 70,  100, 20,  0,  "high_crit",                   100, None),
        ("Blazing Torque",    "fire",      "physical", 80,  100, 10,  0,  None,                           30, "burn"),
        ("Wicked Torque",     "dark",      "physical", 80,  100, 10,  0,  None,                           10, "sleep"),
        ("Noxious Torque",    "poison",    "physical", 100, 100, 10,  0,  None,                           30, "poison"),
        ("Combat Torque",     "fighting",  "physical", 100, 100, 10,  0,  None,                           30, "paralysis"),
        ("Magical Torque",    "fairy",     "physical", 100, 100, 10,  0,  "confuse",                      30, None),
        ("Blood Moon",        "normal",    "special",  140, 100, 5,   0,  "cannot_use_consecutively",    100, None),
        ("Matcha Gotcha",     "grass",     "special",  80,  90,  15,  0,  "drain",                        20, "burn"),
        ("Syrup Bomb",        "grass",     "special",  60,  85,  10,  0,  "lower_speed_each_turn",       100, None),
        ("Ivy Cudgel",        "grass",     "physical", 100, 100, 10,  0,  "type_changes_with_form",      100, None),
        ("Electro Shot",      "electric",  "special",  130, 100, 10,  0,  "charge_raise_spatk",          100, None),
        ("Tera Starstorm",    "normal",    "special",  120, 100, 5,   0,  "stellar_type_change",         100, None),
        ("Fickle Beam",       "dragon",    "special",  80,  100, 5,   0,  "double_power_sometimes",       30, None),
        ("Burning Bulwark",   "fire",      "status",   0,   100, 10,  4,  "protect_burn",                100, None),
        ("Thunderclap",       "electric",  "special",  70,  100, 5,   1,  "fail_if_not_attacking",       100, None),
        ("Mighty Cleave",     "rock",      "physical", 95,  100, 5,   0,  "bypass_protect",              100, None),
        ("Tachyon Cutter",    "steel",     "special",  50,  100, 10,  0,  "hits_twice_never_miss",       100, None),
        ("Hard Press",        "steel",     "physical", 1,   100, 10,  0,  "more_damage_if_hp_target",    100, None),
        ("Dragon Cheer",      "dragon",    "status",   0,   100, 15,  0,  "raise_ally_crit",             100, None),
        ("Alluring Voice",    "fairy",     "special",  80,  100, 10,  0,  "confuse_if_stat_raised",      100, None),
        ("Temper Flare",      "fire",      "physical", 75,  100, 10,  0,  "double_if_last_failed",       100, None),
        ("Supercell Slam",    "electric",  "physical", 100, 95,  15,  0,  "crash",                       100, None),
        ("Psychic Noise",     "psychic",   "special",  75,  100, 10,  0,  "prevent_healing",             100, None),
        ("Upper Hand",        "fighting",  "physical", 65,  100, 15,  3,  "flinch_priority_move",        100, None),
        ("Malignant Chain",   "poison",    "special",  100, 100, 5,   0,  "badly_poison",                 50, None),
        # ── MOVES MANQUANTS ──────────────────────────────────────────
        ("Synthesis",         "grass",     "status",   0,   100, 5,   0,  "heal_weather",                100, None),
        ("Petal Blizzard",    "grass",     "physical", 90,  100, 15,  0,  None,                            0, None),
        ("Dragon Breath",     "dragon",    "special",  60,  100, 20,  0,  None,                           30, "paralysis"),
        ("Fell Stinger",      "bug",       "physical", 50,  100, 25,  0,  "sharply_raise_attack_if_ko",  100, None),
        ("Play Nice",         "normal",    "status",   0,   100, 20,  0,  "lower_attack",                100, None),
        ("Electro Ball",      "electric",  "special",  1,   100, 10,  0,  "speed_ratio_power",           100, None),
        ("Healing Wish",      "psychic",   "status",   0,   100, 10,  0,  "faint_heal_next",             100, None),
        ("Round",             "normal",    "special",  60,  100, 15,  0,  "double_if_ally_used",         100, None),
        ("Last Resort",       "normal",    "physical", 140, 100, 5,   0,  "only_after_all_moves",        100, None),
        ("Cross Poison",      "poison",    "physical", 70,  100, 20,  0,  "high_crit",                   10, "poison"),
        ("Punishment",        "dark",      "physical", 60,  100, 5,   0,  "power_per_stat_boost",        100, None),
        ("Swagger",           "normal",    "status",   0,   85,  15,  0,  "confuse_raise_attack",        100, None),
        ("Extremespeed",      "normal",    "physical", 80,  100, 5,   2,  None,                            0, None),
        ("Circle Throw",      "fighting",  "physical", 60,  90,  10,  -6, "force_switch",                100, None),
        ("Ally Switch",       "psychic",   "status",   0,   100, 15,  2,  "swap_position_ally",          100, None),
        ("Belch",             "poison",    "special",  120, 90,  10,  0,  "requires_berry_eaten",        100, None),
        ("Heavy Slam",        "steel",     "physical", 1,   100, 10,  0,  "weight_based",                100, None),
        ("Brave Bird",        "flying",    "physical", 120, 100, 15,  0,  "recoil",                      100, None),
        ("Whirlpool",         "water",     "special",  35,  85,  15,  0,  "trap",                        100, None),
        ("Brine",             "water",     "special",  65,  100, 10,  0,  "double_if_half_hp",           100, None),
        ("Icicle Crash",      "ice",       "physical", 85,  90,  10,  0,  "flinch",                       30, None),
        ("Rock Tomb",         "rock",      "physical", 60,  95,  15,  0,  "lower_speed",                 100, None),
        ("Iron Tail",         "steel",     "physical", 100, 75,  15,  0,  "lower_defense",                30, None),
        ("Natural Gift",      "normal",    "physical", 1,   100, 15,  0,  "berry_power_type",            100, None),
        ("Stomping Tantrum",  "ground",    "physical", 75,  100, 10,  0,  "double_if_last_failed",       100, None),
        ("Jab",               "fighting",  "physical", 30,  100, 25,  0,  None,                            0, None),
        ("Strange Steam",     "fairy",     "special",  90,  95,  10,  0,  "confuse",                      20, None),
        ("Chip Away",         "normal",    "physical", 70,  100, 20,  0,  "ignore_stat_changes",         100, None),
        ("Drill Run",         "ground",    "physical", 80,  95,  10,  0,  "high_crit",                   100, None),
        ("Soak",              "water",     "status",   0,   100, 20,  0,  "change_type_water",           100, None),
        ("Psywave",           "psychic",   "special",  1,   100, 15,  0,  "random_damage",               100, None),
        ("Covet",             "normal",    "physical", 60,  100, 25,  0,  "steal_item",                  100, None),
        ("Trump Card",        "normal",    "special",  1,   100, 5,   0,  "power_low_pp",                100, None),
        ("Muddy Water",       "water",     "special",  90,  85,  10,  0,  "lower_accuracy",               30, None),
        ("Snore",             "normal",    "special",  50,  100, 15,  0,  "only_asleep_flinch",           30, None),
    ]

    created_count = 0
    skipped_count = 0
    error_count = 0

    for move_data in gen9_moves:
        name, type_name, category, power, accuracy, pp, priority, effect, effect_chance, inflicts_status = move_data
        try:
            move_type = get_type(type_name)
            _, created = PokemonMove.objects.get_or_create(
                name=name,
                defaults={
                    "type": move_type,
                    "category": category,
                    "power": power,
                    "accuracy": accuracy,
                    "pp": pp,
                    "max_pp": pp,
                    "priority": priority,
                    "effect": effect,
                    "effect_chance": effect_chance,
                    "inflicts_status": inflicts_status,
                },
            )
            if created:
                created_count += 1
                logging.info(f"  [+] Move créé: {name}")
            else:
                skipped_count += 1
        except Exception as e:
            logging.warning(f"  [!] Erreur pour move '{name}': {e}")
            error_count += 1

    logging.info("=" * 70)
    logging.info(f"[✓] {created_count} moves Gen 9 créés")
    logging.info(f"    {skipped_count} déjà présents, {error_count} erreurs")
    logging.info("=" * 70)


if __name__ == "__main__":
    add_missing_gen9_moves()