# Generated by Django 4.2.13 on 2026-02-13 15:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('item_type', models.CharField(choices=[('potion', 'Potion'), ('pokeball', 'Poké Ball'), ('evolution', "Pierre d'évolution"), ('status', 'Soin de statut'), ('battle', 'Objet de combat'), ('held', 'Objet tenu'), ('key', 'Objet clé')], max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('heal_amount', models.IntegerField(default=0)),
                ('heal_percentage', models.IntegerField(default=0)),
                ('cures_status', models.BooleanField(default=False)),
                ('specific_status', models.CharField(blank=True, max_length=20, null=True)),
                ('catch_rate_modifier', models.FloatField(default=1.0)),
                ('evolves_pokemon', models.CharField(blank=True, max_length=50, null=True)),
                ('held_effect', models.CharField(blank=True, max_length=100, null=True)),
                ('is_consumable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Objet',
                'verbose_name_plural': 'Objets',
            },
        ),
        migrations.CreateModel(
            name='PlayablePokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=12, null=True)),
                ('level', models.IntegerField(default=5)),
                ('current_exp', models.IntegerField(default=0)),
                ('max_hp', models.IntegerField()),
                ('current_hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('special_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('iv_hp', models.IntegerField(default=0)),
                ('iv_attack', models.IntegerField(default=0)),
                ('iv_defense', models.IntegerField(default=0)),
                ('iv_special_attack', models.IntegerField(default=0)),
                ('iv_special_defense', models.IntegerField(default=0)),
                ('iv_speed', models.IntegerField(default=0)),
                ('ev_hp', models.IntegerField(default=0)),
                ('ev_attack', models.IntegerField(default=0)),
                ('ev_defense', models.IntegerField(default=0)),
                ('ev_special_attack', models.IntegerField(default=0)),
                ('ev_special_defense', models.IntegerField(default=0)),
                ('ev_speed', models.IntegerField(default=0)),
                ('nature', models.CharField(default='Hardy', max_length=20)),
                ('status_condition', models.CharField(blank=True, choices=[('paralysis', 'Paralysie'), ('poison', 'Poison'), ('burn', 'Brûlure'), ('freeze', 'Gel'), ('sleep', 'Sommeil')], max_length=20, null=True)),
                ('sleep_turns', models.IntegerField(default=0)),
                ('attack_stage', models.IntegerField(default=0)),
                ('defense_stage', models.IntegerField(default=0)),
                ('special_attack_stage', models.IntegerField(default=0)),
                ('special_defense_stage', models.IntegerField(default=0)),
                ('speed_stage', models.IntegerField(default=0)),
                ('accuracy_stage', models.IntegerField(default=0)),
                ('evasion_stage', models.IntegerField(default=0)),
                ('friendship', models.IntegerField(default=70)),
                ('original_trainer', models.CharField(max_length=50)),
                ('caught_location', models.CharField(blank=True, max_length=100, null=True)),
                ('pokeball_used', models.CharField(default='pokeball', max_length=20)),
                ('party_position', models.IntegerField(blank=True, null=True)),
                ('is_in_party', models.BooleanField(default=True)),
                ('held_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_by', to='myPokemonApp.item')),
            ],
            options={
                'verbose_name': 'Pokémon (Jouable)',
                'verbose_name_plural': 'Pokémon (Jouables)',
                'ordering': ['party_position'],
            },
        ),
        migrations.CreateModel(
            name='PokemonMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('physical', 'Physique'), ('special', 'Spécial'), ('status', 'Statut')], max_length=10)),
                ('power', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pp', models.IntegerField(default=5)),
                ('max_pp', models.IntegerField(default=5)),
                ('priority', models.IntegerField(default=0)),
                ('effect', models.CharField(blank=True, max_length=50, null=True)),
                ('effect_chance', models.IntegerField(default=0)),
                ('inflicts_status', models.CharField(blank=True, max_length=20, null=True)),
                ('stat_changes', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Capacité',
                'verbose_name_plural': 'Capacités',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('trainer_type', models.CharField(choices=[('player', 'Joueur'), ('rival', 'Rival'), ('gym_leader', "Champion d'Arène"), ('elite_four', 'Conseil des 4'), ('champion', 'Maître'), ('trainer', 'Dresseur'), ('wild', 'Sauvage')], max_length=20)),
                ('money', models.IntegerField(default=3000)),
                ('badges', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('is_defeated', models.BooleanField(default=False)),
                ('can_rebattle', models.BooleanField(default=False)),
                ('intro_text', models.TextField(blank=True, null=True)),
                ('defeat_text', models.TextField(blank=True, null=True)),
                ('victory_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dresseur',
                'verbose_name_plural': 'Dresseurs',
            },
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('strong_against', models.ManyToManyField(blank=True, related_name='weak_against', to='myPokemonApp.pokemontype')),
            ],
            options={
                'verbose_name': 'Type de Pokémon',
                'verbose_name_plural': 'Types de Pokémon',
            },
        ),
        migrations.CreateModel(
            name='PokemonMoveInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_pp', models.IntegerField()),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPokemonApp.pokemonmove')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPokemonApp.playablepokemon')),
            ],
            options={
                'unique_together': {('pokemon', 'move')},
            },
        ),
        migrations.AddField(
            model_name='pokemonmove',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPokemonApp.pokemontype'),
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('pokedex_number', models.IntegerField(unique=True)),
                ('base_hp', models.IntegerField()),
                ('base_attack', models.IntegerField()),
                ('base_defense', models.IntegerField()),
                ('base_special_attack', models.IntegerField()),
                ('base_special_defense', models.IntegerField()),
                ('base_speed', models.IntegerField()),
                ('catch_rate', models.IntegerField(default=45)),
                ('base_experience', models.IntegerField()),
                ('growth_rate', models.CharField(default='medium_fast', max_length=20)),
                ('sprite_url', models.URLField(blank=True, null=True)),
                ('primary_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_pokemon', to='myPokemonApp.pokemontype')),
                ('secondary_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_pokemon', to='myPokemonApp.pokemontype')),
            ],
            options={
                'verbose_name': 'Pokémon (Base)',
                'verbose_name_plural': 'Pokémon (Bases)',
                'ordering': ['pokedex_number'],
            },
        ),
        migrations.AddField(
            model_name='playablepokemon',
            name='moves',
            field=models.ManyToManyField(related_name='known_by', through='myPokemonApp.PokemonMoveInstance', to='myPokemonApp.pokemonmove'),
        ),
        migrations.AddField(
            model_name='playablepokemon',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPokemonApp.pokemon'),
        ),
        migrations.AddField(
            model_name='playablepokemon',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_team', to='myPokemonApp.trainer'),
        ),
        migrations.CreateModel(
            name='GymLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(max_length=50)),
                ('gym_city', models.CharField(max_length=50)),
                ('badge_name', models.CharField(max_length=50)),
                ('badge_order', models.IntegerField(unique=True)),
                ('specialty_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_leaders', to='myPokemonApp.pokemontype')),
                ('tm_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myPokemonApp.pokemonmove')),
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gym_info', to='myPokemonApp.trainer')),
            ],
            options={
                'verbose_name': "Champion d'Arène",
                'verbose_name_plural': "Champions d'Arène",
                'ordering': ['badge_order'],
            },
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_type', models.CharField(choices=[('wild', 'Pokémon sauvage'), ('trainer', 'Dresseur'), ('gym', 'Arène'), ('elite_four', 'Conseil des 4')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('current_turn', models.IntegerField(default=1)),
                ('weather', models.CharField(blank=True, max_length=20, null=True)),
                ('terrain', models.CharField(blank=True, max_length=20, null=True)),
                ('battle_log', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('opponent_pokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_as_opponent_pokemon', to='myPokemonApp.playablepokemon')),
                ('opponent_trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_opponent', to='myPokemonApp.trainer')),
                ('player_pokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_as_player_pokemon', to='myPokemonApp.playablepokemon')),
                ('player_trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_player', to='myPokemonApp.trainer')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_battles', to='myPokemonApp.trainer')),
            ],
            options={
                'verbose_name': 'Combat',
                'verbose_name_plural': 'Combats',
            },
        ),
        migrations.CreateModel(
            name='TrainerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPokemonApp.item')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='myPokemonApp.trainer')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'unique_together': {('trainer', 'item')},
            },
        ),
        migrations.CreateModel(
            name='PokemonLearnableMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_learned', models.IntegerField()),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPokemonApp.pokemonmove')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnable_moves', to='myPokemonApp.pokemon')),
            ],
            options={
                'ordering': ['level_learned'],
                'unique_together': {('pokemon', 'move')},
            },
        ),
        migrations.CreateModel(
            name='PokemonEvolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('level', 'Niveau'), ('stone', 'Pierre'), ('trade', 'Échange'), ('friendship', 'Bonheur'), ('item', 'Objet')], max_length=20)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('evolves_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolutions_to', to='myPokemonApp.pokemon')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolutions_from', to='myPokemonApp.pokemon')),
                ('required_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myPokemonApp.item')),
            ],
            options={
                'verbose_name': 'Évolution',
                'unique_together': {('pokemon', 'evolves_to')},
            },
        ),
    ]
