# Generated by Django 4.2.13 on 2024-08-24 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('pp', models.IntegerField()),
                ('attackPower', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('type', models.TextField()),
                ('effect', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('level', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('specialAttack', models.IntegerField()),
                ('specialDefense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('catchRate', models.IntegerField()),
                ('baseExperience', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('maxHp', models.IntegerField()),
                ('status', models.TextField()),
                ('moves', models.ManyToManyField(to='myPokemonApp.pokemonmove', verbose_name="Pokemon's List of moves")),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPokemonApp.pokemontype', verbose_name='PokemonType')),
            ],
        ),
    ]
