# Generated by Django 4.2.13 on 2026-02-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='battle_state',
            field=models.JSONField(default=dict),
        ),
    ]
