# Generated by Django 4.2.13 on 2026-02-14 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shop_type', models.CharField(choices=[('pokemart', 'PokéMart'), ('department', 'Grand Magasin'), ('special', 'Boutique Spéciale')], default='pokemart', max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('shopkeeper_sprite', models.CharField(blank=True, max_length=100, null=True)),
                ('shopkeeper_greeting', models.TextField(default='Bienvenue au PokéMart!')),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'Boutiques',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Achat'), ('sell', 'Vente')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myPokemonApp.item')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myPokemonApp.shop')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='myPokemonApp.trainer')),
            ],
            options={
                'verbose_name': 'Transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=-1)),
                ('unlock_badge_required', models.IntegerField(default=0)),
                ('custom_price', models.IntegerField(blank=True, null=True)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPokemonApp.item')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='myPokemonApp.shop')),
            ],
            options={
                'verbose_name': 'Inventaire Boutique',
                'ordering': ['-is_featured', '-is_new', 'item__item_type', 'item__name'],
                'unique_together': {('shop', 'item')},
            },
        ),
    ]
