# Generated by Django 4.2.13 on 2026-02-23 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0002_battle_battle_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_id', models.CharField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quest_type', models.CharField(choices=[('main', 'Quête principale'), ('side', 'Quête secondaire'), ('rival', 'Rencontre Rival'), ('hm', 'Obtention CS')], default='main', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('trigger_type', models.CharField(choices=[('visit_zone', 'Visiter une zone'), ('defeat_trainer', 'Battre un dresseur'), ('defeat_gym', "Battre un Champion d'Arène"), ('have_item', 'Posséder un objet'), ('give_item', "Remettre un objet à quelqu'un"), ('collect_badge', 'Obtenir un badge'), ('story_flag', 'Flag scénaristique'), ('auto', 'Automatique')], default='auto', max_length=20)),
                ('trigger_flag', models.CharField(blank=True, max_length=60)),
                ('reward_money', models.IntegerField(default=0)),
                ('reward_flag', models.CharField(blank=True, max_length=60)),
                ('objective_text', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(default='fa-scroll', max_length=50)),
                ('prerequisite_quests', models.ManyToManyField(blank=True, related_name='unlocks_quests', to='myPokemonApp.quest')),
                ('reward_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_rewards', to='myPokemonApp.item')),
                ('trigger_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_triggers', to='myPokemonApp.item')),
                ('trigger_trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_triggers', to='myPokemonApp.trainer')),
            ],
            options={
                'verbose_name': 'Quête',
                'verbose_name_plural': 'Quêtes',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='zone',
            name='has_floors',
            field=models.BooleanField(default=False, help_text='Bâtiment multi-étages'),
        ),
        migrations.AddField(
            model_name='zone',
            name='required_flags',
            field=models.JSONField(blank=True, default=list, help_text='Flags story requis. Ex: ["has_silph_scope"]'),
        ),
        migrations.AddField(
            model_name='zone',
            name='required_hm',
            field=models.CharField(blank=True, choices=[('', 'Aucune'), ('cut', 'CS01 Coupe'), ('fly', 'CS02 Vol'), ('surf', 'CS03 Surf'), ('strength', 'CS04 Force'), ('flash', 'CS05 Flash')], default='', help_text="CS qu'un Pokémon de l'équipe doit connaître", max_length=10),
        ),
        migrations.AddField(
            model_name='zoneconnection',
            name='passage_message',
            field=models.CharField(blank=True, help_text='Message affiché quand le passage est bloqué', max_length=200),
        ),
        migrations.AddField(
            model_name='zoneconnection',
            name='required_flag',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='zoneconnection',
            name='required_hm',
            field=models.CharField(blank=True, choices=[('', 'Aucune'), ('cut', 'CS01 Coupe'), ('fly', 'CS02 Vol'), ('surf', 'CS03 Surf'), ('strength', 'CS04 Force'), ('flash', 'CS05 Flash')], default='', help_text='CS requise pour traverser (ex: cut pour un arbre)', max_length=10),
        ),
        migrations.AlterField(
            model_name='zone',
            name='required_item',
            field=models.ForeignKey(blank=True, help_text='Objet clé requis (ex: Abonnement Vélo)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones_requiring_item', to='myPokemonApp.item'),
        ),
        migrations.CreateModel(
            name='ZoneFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField()),
                ('floor_name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('required_flag', models.CharField(blank=True, max_length=60)),
                ('required_flag_label', models.CharField(blank=True, help_text='Message affiché si le flag est absent', max_length=100)),
                ('is_safe', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='myPokemonApp.zone')),
            ],
            options={
                'verbose_name': 'Étage',
                'verbose_name_plural': 'Étages',
                'ordering': ['zone', 'floor_number'],
                'unique_together': {('zone', 'floor_number')},
            },
        ),
        migrations.CreateModel(
            name='RivalEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_battle_text', models.TextField(blank=True)),
                ('post_battle_text', models.TextField(blank=True)),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rival_encounters', to='myPokemonApp.zonefloor')),
                ('quest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rival_encounter', to='myPokemonApp.quest')),
                ('rival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rival_encounters', to='myPokemonApp.trainer')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rival_encounters', to='myPokemonApp.zone')),
            ],
            options={
                'verbose_name': 'Rencontre Rival',
                'verbose_name_plural': 'Rencontres Rival',
            },
        ),
        migrations.AddField(
            model_name='quest',
            name='trigger_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_triggers', to='myPokemonApp.zone'),
        ),
        migrations.AddField(
            model_name='zone',
            name='required_quest',
            field=models.ForeignKey(blank=True, help_text='Quête complétée requise', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gated_zones', to='myPokemonApp.quest'),
        ),
        migrations.CreateModel(
            name='QuestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('locked', 'Verrouillée'), ('available', 'Disponible'), ('active', 'En cours'), ('completed', 'Terminée')], default='locked', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='myPokemonApp.quest')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_progress', to='myPokemonApp.trainer')),
            ],
            options={
                'verbose_name': 'Progression de quête',
                'ordering': ['quest__order'],
                'unique_together': {('trainer', 'quest')},
            },
        ),
    ]
