# Generated by Django 4.2.13 on 2024-09-23 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0002_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonLearnableMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LearnableAtLevel', models.IntegerField()),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPokemonApp.pokemonmove')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPokemonApp.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='PlayablePokemon',
            fields=[
                ('pokemon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myPokemonApp.pokemon')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='myPokemonApp.trainer')),
            ],
            bases=('myPokemonApp.pokemon',),
        ),
    ]
