# Generated by Django 4.2.13 on 2026-02-14 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0002_shop_transaction_shopinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Centre Pokémon', max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('nurse_name', models.CharField(default='Infirmière Joy', max_length=50)),
                ('nurse_greeting', models.TextField(default='Bienvenue au Centre Pokémon ! Puis-je soigner vos Pokémon ?')),
                ('nurse_healing_message', models.TextField(default='Vos Pokémon ont été complètement soignés ! Revenez quand vous voulez !')),
                ('nurse_farewell', models.TextField(default='Nous espérons vous revoir bientôt !')),
                ('nurse_sprite', models.CharField(blank=True, max_length=100, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('healing_cost', models.IntegerField(default=0)),
                ('total_healings', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Centre Pokémon',
                'verbose_name_plural': 'Centres Pokémon',
            },
        ),
        migrations.CreateModel(
            name='NurseDialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialogue_type', models.CharField(choices=[('greeting', 'Salutation'), ('healing', 'Pendant le soin'), ('complete', 'Soin terminé'), ('farewell', 'Au revoir'), ('special', 'Spécial')], max_length=20)),
                ('text', models.TextField()),
                ('min_badges', models.IntegerField(default=0)),
                ('max_badges', models.IntegerField(default=8)),
                ('rarity', models.IntegerField(default=5)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='myPokemonApp.pokemoncenter')),
            ],
            options={
                'verbose_name': 'Dialogue Infirmière',
                'verbose_name_plural': 'Dialogues Infirmière',
            },
        ),
        migrations.CreateModel(
            name='CenterVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('pokemon_healed', models.IntegerField()),
                ('cost', models.IntegerField(default=0)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='myPokemonApp.pokemoncenter')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_visits', to='myPokemonApp.trainer')),
            ],
            options={
                'verbose_name': 'Visite Centre',
                'verbose_name_plural': 'Visites Centres',
                'ordering': ['-visited_at'],
            },
        ),
    ]
