# Generated by Django 4.2.13 on 2026-02-15 09:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0003_pokemoncenter_nursedialogue_centervisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokeballItem',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myPokemonApp.item')),
                ('catch_rate_multiplier', models.FloatField(default=1.0, help_text='Multiplicateur (1.0 = Poké Ball normale)')),
                ('bonus_on_status', models.CharField(blank=True, help_text='Bonus si Pokémon a ce status (burn, sleep, etc.)', max_length=20)),
                ('guaranteed_capture', models.BooleanField(default=False, help_text='Master Ball')),
                ('critical_catch_bonus', models.FloatField(default=0.0, help_text='Chance de capture critique')),
                ('bonus_on_type', models.ForeignKey(blank=True, help_text='Bonus sur un type spécifique', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myPokemonApp.pokemontype')),
            ],
            options={
                'verbose_name': 'Poké Ball (Stats)',
                'verbose_name_plural': 'Poké Balls (Stats)',
            },
        ),
        migrations.CreateModel(
            name='CaptureJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('attempts_before_success', models.IntegerField(default=1)),
                ('level_at_capture', models.IntegerField()),
                ('hp_at_capture', models.IntegerField()),
                ('is_first_catch', models.BooleanField(default=False, help_text='Premier de cette espèce')),
                ('is_shiny', models.BooleanField(default=False)),
                ('is_critical_catch', models.BooleanField(default=False, help_text='Capture critique (1 shake)')),
                ('ball_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myPokemonApp.item')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_entry', to='myPokemonApp.playablepokemon')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_journal', to='myPokemonApp.trainer')),
            ],
            options={
                'verbose_name': 'Entrée Journal de Capture',
                'verbose_name_plural': 'Journal de Captures',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='CaptureAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_level', models.IntegerField()),
                ('pokemon_hp_percent', models.FloatField(help_text='% HP au moment de la capture')),
                ('pokemon_status', models.CharField(blank=True, max_length=20, null=True)),
                ('success', models.BooleanField()),
                ('capture_rate', models.FloatField(help_text='Probabilité calculée (0-1)')),
                ('shakes', models.IntegerField(default=0, help_text='Nombre de shakes avant capture/échec')),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ball_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myPokemonApp.item')),
                ('battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myPokemonApp.battle')),
                ('pokemon_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPokemonApp.pokemon')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_attempts', to='myPokemonApp.trainer')),
            ],
            options={
                'verbose_name': 'Tentative de Capture',
                'verbose_name_plural': 'Tentatives de Capture',
                'ordering': ['-attempted_at'],
            },
        ),
    ]
