# Generated by Django 4.2.13 on 2024-09-23 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0003_pokemonlearnablemove_playablepokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonlearnablemove',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnable_moves', to='myPokemonApp.pokemon'),
        ),
        migrations.CreateModel(
            name='PokemonEvolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolutionLevel', models.IntegerField()),
                ('evolvesTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolved_from', to='myPokemonApp.pokemon')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolutions', to='myPokemonApp.pokemon')),
            ],
        ),
    ]
