# Generated by Django 4.2.13 on 2026-02-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0004_pokeballitem_capturejournal_captureattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokeballitem',
            name='catch_rate_multiplier',
        ),
    ]
