# Generated by Django 4.2.13 on 2026-03-02 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0005_alter_rivalencounter_rival_rivaltemplate_playerrival'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('effect_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('trigger', models.CharField(choices=[('on_switch_in', "À l'entrée en combat"), ('on_switch_out', 'Au retrait du combat'), ('on_damage_taken', 'À la réception de dégâts'), ('on_attack', "Lors d'une attaque"), ('on_status', "Lors d'un changement de statut"), ('modify_stat', 'Modificateur de stats'), ('end_of_turn', 'Fin de tour'), ('passive', 'Passif permanent'), ('on_capture', "Lors d'une capture")], default='passive', max_length=20)),
            ],
            options={
                'verbose_name': 'Talent',
                'verbose_name_plural': 'Talents',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='playablepokemon',
            name='is_hidden_ability',
            field=models.BooleanField(default=False, verbose_name='Talent caché ?'),
        ),
        migrations.AddField(
            model_name='playablepokemon',
            name='ability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon_instances', to='myPokemonApp.ability', verbose_name='Talent'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ability_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species_slot_1', to='myPokemonApp.ability', verbose_name='Talent 1'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ability_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species_slot_2', to='myPokemonApp.ability', verbose_name='Talent 2'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='hidden_ability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species_hidden', to='myPokemonApp.ability', verbose_name='Talent Caché'),
        ),
    ]
