# Generated by Django 4.2.13 on 2026-02-15 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0005_remove_pokeballitem_catch_rate_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='is_npc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainer',
            name='npc_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trainer',
            name='sprite_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='TrainerBattleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_won', models.BooleanField()),
                ('money_earned', models.IntegerField(default=0)),
                ('fought_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myPokemonApp.battle')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_history_as_opponent', to='myPokemonApp.trainer')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_history_as_player', to='myPokemonApp.trainer')),
            ],
            options={
                'verbose_name': 'Historique Combat',
                'ordering': ['-fought_at'],
            },
        ),
        migrations.CreateModel(
            name='GameSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(default=1, help_text='Numéro du slot (1-3)')),
                ('save_name', models.CharField(blank=True, help_text='Nom personnalisé', max_length=100)),
                ('play_time', models.IntegerField(default=0, help_text='Temps de jeu en secondes')),
                ('current_location', models.CharField(default='Bourg Palette', max_length=100)),
                ('last_pokemon_center', models.CharField(default='Bourg Palette', max_length=100)),
                ('story_flags', models.JSONField(default=dict, help_text='Événements complétés')),
                ('defeated_trainers', models.JSONField(default=list, help_text='IDs des dresseurs battus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_saved', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_saves', to='myPokemonApp.trainer')),
            ],
            options={
                'verbose_name': 'Sauvegarde',
                'ordering': ['slot'],
                'unique_together': {('trainer', 'slot')},
            },
        ),
    ]
