# Generated by Django 4.2.13 on 2026-02-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0006_trainer_is_npc_trainer_npc_class_trainer_sprite_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesave',
            name='game_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
