# Generated by Django 4.2.13 on 2026-03-04 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0007_trainer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['item_type', 'tm_number', 'name'], 'verbose_name': 'Objet', 'verbose_name_plural': 'Objets'},
        ),
        migrations.AlterModelOptions(
            name='pokemonlearnablemove',
            options={'ordering': ['learn_method', 'level_learned'], 'verbose_name': 'Capacité apprennable', 'verbose_name_plural': 'Capacités apprenables'},
        ),
        migrations.AlterUniqueTogether(
            name='pokemonlearnablemove',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='item',
            name='tm_move',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tm_items', to='myPokemonApp.pokemonmove', verbose_name='Capacité enseignée'),
        ),
        migrations.AddField(
            model_name='item',
            name='tm_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numéro CT/CS'),
        ),
        migrations.AddField(
            model_name='pokemonlearnablemove',
            name='learn_method',
            field=models.CharField(choices=[('level', 'Montée de niveau'), ('tm', 'CT / CS (TM/HM)')], default='level', max_length=10, verbose_name="Méthode d'apprentissage"),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('potion', 'Potion'), ('pokeball', 'Poké Ball'), ('evolution', "Pierre d'évolution"), ('status', 'Soin de statut'), ('battle', 'Objet de combat'), ('held', 'Objet tenu'), ('key', 'Objet clé'), ('tm', 'CT (Capsule Technique)'), ('cs', 'CS (Capsule Secrète)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pokemonlearnablemove',
            name='level_learned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='pokemonlearnablemove',
            unique_together={('pokemon', 'move', 'learn_method')},
        ),
    ]
