# Generated by Django 4.2.13 on 2026-02-16 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0007_gamesave_game_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('combat', 'Combat'), ('capture', 'Capture'), ('collection', 'Collection'), ('exploration', 'Exploration'), ('progression', 'Progression')], max_length=20)),
                ('required_value', models.IntegerField(default=1)),
                ('reward_money', models.IntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('reward_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myPokemonApp.item')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('zone_type', models.CharField(choices=[('route', 'Route'), ('city', 'Ville'), ('cave', 'Grotte'), ('forest', 'Forêt'), ('water', 'Mer'), ('building', 'Bâtiment')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('recommended_level_min', models.IntegerField(default=1)),
                ('recommended_level_max', models.IntegerField(default=10)),
                ('order', models.IntegerField(default=0, help_text='Ordre dans la progression')),
                ('image', models.CharField(blank=True, max_length=200)),
                ('music', models.CharField(blank=True, max_length=200)),
                ('is_safe_zone', models.BooleanField(default=False, help_text='Pas de wild battles')),
                ('has_pokemon_center', models.BooleanField(default=False)),
                ('has_shop', models.BooleanField(default=False)),
                ('required_badge', models.ForeignKey(blank=True, help_text='Badge requis pour accéder', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myPokemonApp.gymleader')),
                ('required_item', models.ForeignKey(blank=True, help_text='Item requis (ex: Bicyclette)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myPokemonApp.item')),
            ],
            options={
                'verbose_name': 'Zone',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WildPokemonSpawn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spawn_rate', models.FloatField(default=10.0, help_text="% de chance d'apparition (total zone = 100%)")),
                ('level_min', models.IntegerField(default=2)),
                ('level_max', models.IntegerField(default=5)),
                ('encounter_type', models.CharField(choices=[('grass', 'Hautes herbes'), ('water', 'Surf'), ('fishing', 'Pêche'), ('cave', 'Grotte')], default='grass', max_length=20)),
                ('time_of_day', models.CharField(blank=True, choices=[('', 'Toujours'), ('morning', 'Matin'), ('day', 'Jour'), ('night', 'Nuit')], default='', max_length=20)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPokemonApp.pokemon')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wild_spawns', to='myPokemonApp.zone')),
            ],
            options={
                'verbose_name': 'Spawn Pokémon',
                'ordering': ['-spawn_rate'],
            },
        ),
        migrations.CreateModel(
            name='PlayerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPokemonApp.zone')),
                ('last_pokemon_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='myPokemonApp.zone')),
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_location', to='myPokemonApp.trainer')),
                ('visited_zones', models.ManyToManyField(blank=True, related_name='visitors', to='myPokemonApp.zone')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bidirectional', models.BooleanField(default=True)),
                ('from_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='myPokemonApp.zone')),
                ('to_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='myPokemonApp.zone')),
            ],
            options={
                'unique_together': {('from_zone', 'to_zone')},
            },
        ),
        migrations.CreateModel(
            name='TrainerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_progress', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPokemonApp.achievement')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='myPokemonApp.trainer')),
            ],
            options={
                'unique_together': {('trainer', 'achievement')},
            },
        ),
    ]
