# Generated by Django 4.2.13 on 2026-03-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0008_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='battle_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
