# Generated by Django 4.2.13 on 2026-02-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0008_achievement_zone_wildpokemonspawn_playerlocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playablepokemon',
            name='is_shiny',
            field=models.BooleanField(default=False),
        ),
    ]
