# Generated by Django 4.2.13 on 2026-02-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0009_playablepokemon_is_shiny'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinventory',
            name='unlock_condition',
            field=models.CharField(choices=[('none', 'Aucune condition'), ('has_pokedex', 'Avoir reçu un Pokédex')], default='none', help_text='Condition spéciale requise (ex. avoir reçu un Pokédex)', max_length=30),
        ),
    ]
