# Generated by Django 4.2.13 on 2026-03-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0009_battle_battle_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonmoveinstance',
            name='source',
            field=models.CharField(choices=[('level', 'Montée de niveau'), ('tm', 'CT (Technical Machine)'), ('hm', 'CS (Hidden Machine)'), ('tutor', 'Tuteur de capacité'), ('egg', 'Capacité Œuf'), ('other', 'Autre')], default='level', max_length=10),
        ),
    ]
