# Generated by Django 4.2.13 on 2026-03-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0010_pokemonmoveinstance_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='ev_yield_attack',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='EV Attaque'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ev_yield_defense',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='EV Défense'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ev_yield_hp',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='EV HP'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ev_yield_special_attack',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='EV Att. Spé.'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ev_yield_special_defense',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='EV Déf. Spé.'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ev_yield_speed',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='EV Vitesse'),
        ),
    ]
