# Generated by Django 4.2.13 on 2026-03-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0016_remove_defeatedtrainer_unique_defeated_trainer_per_save_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['player_trainer', 'is_active'], name='idx_battle_trainer_active'),
        ),
        migrations.AddIndex(
            model_name='gamesave',
            index=models.Index(fields=['trainer', 'is_active'], name='idx_gamesave_trainer_active'),
        ),
        migrations.AddIndex(
            model_name='playablepokemon',
            index=models.Index(fields=['trainer', 'is_in_party'], name='idx_pp_trainer_party'),
        ),
    ]
