# Generated by Django 4.2.13 on 2026-03-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0017_battle_idx_battle_trainer_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='ai_flags',
            field=models.JSONField(blank=True, default=list, help_text='Flags IA Gen 4 : ["basic", "evaluate_attack", "expert", ...]'),
        ),
    ]
