# Generated by Django 4.2.13 on 2026-03-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPokemonApp', '0018_trainer_ai_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='playablepokemon',
            name='gender',
            field=models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle'), ('N', 'Sans genre')], default='M', help_text='M = mâle, F = femelle, N = sans genre', max_length=1),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='gender_ratio',
            field=models.FloatField(default=0.5, help_text="Probabilité d'être mâle (0.0-1.0) ou -1 pour sans genre."),
        ),
    ]
